Give more granular reasons for project failure
newtontechnologies/beey-data-exchange-model pull request #18
Opened 2024-01-23 22:12 UTC by richardklapac

2024-01-29 10:17 UTC, kudlosh requested changes

2024-01-29 10:17 UTC, kudlosh commented on Beey.DataExchangeModel.Common/Project/ProjectErrorCategory.cs
> +public enum FFmpegExitCodes
Tohle nedává smysl jako enum, ale spíš jako třída s konstantama.

2024-01-29 10:17 UTC, kudlosh commented on Beey.DataExchangeModel.Common/Project/ProjectErrorCategory.cs
> +// TODO move away
Tohle by mělo být přímo v backendu, protože tyhle hodnoty zvenku nebudou nikdy potřeba.

Blbý, že nemáme třídu pro FFmpeg. Hele, tak do adresáře _ErrorHandling_ přidej statickou třídu s těmahle kódama. Tam by se to docela hodilo 🙂

2024-01-30 14:58 UTC, richardklapac commented
Ah, teď jsem si všimnul těch review requests. Tak to přesunu ještě jednou. :smile:

2024-03-19 09:51 UTC, merged